#!/bin/sh
# DefendOS – live-build auto/config
# Exécuté par 'lb config' ou 'bash auto/config'
# Référence : https://live-team.pages.debian.net/live-manual/

set -e

# Aller dans le répertoire du profil
cd "$(dirname "$0")/.."

lb config \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --apt-recommends false \
    --apt-source-archives false \
    \
    --bootappend-live \
        "boot=live components quiet splash \
         username=root hostname=defendos \
         toram \
         systemd.unified_cgroup_hierarchy=1" \
    \
    --bootappend-live-failsafe \
        "boot=live components nox11 noconfig \
         username=root hostname=defendos" \
    \
    --debian-installer none \
    --debian-installer-distribution bookworm \
    \
    --iso-application "DefendOS – Cybersecurity Live OS" \
    --iso-publisher "DefendOS Project" \
    --iso-volume "DefendOS_$(date +%Y%m)" \
    \
    --linux-flavours amd64 \
    \
    --mirror-bootstrap    "http://deb.debian.org/debian/" \
    --mirror-chroot       "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary       "http://deb.debian.org/debian/" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    \
    --image-name "defendos" \
    --checksums sha256 \
    \
    --security true \
    --updates true \
    \
    "${@}"
