# DefendOS – SSH Hardening
# /etc/ssh/sshd_config.d/99-defendos.conf

Protocol 2
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

ClientAliveInterval 300
ClientAliveCountMax 0

AllowTcpForwarding no
X11Forwarding no
PermitTunnel no
AllowAgentForwarding no
PrintMotd no

# Chiffrement fort uniquement
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Bannière
Banner /etc/issue.net
